name: Crear .env

on:
  push:
    branches:
      - prueba-workflow

jobs:
  createEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env
        run: |
          touch .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "DB_AUTH_TOKEN=${{ secrets.DB_AUTH_TOKEN }}" >> .env
          echo "JWT_PASSWORD=${{ secrets.JWT_PASSWORD }}" >> .env
          echo "URL_DATABASE=${{ secrets.URL_DATABASE }}" >> .env
      - name: List files
        run: ls -a