name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2
    env:
      EC2_IP: ${{ secrets.EC2_IP }}
      EC2_USER: ${{ secrets.EC2_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa 

      - name: Create .env
        run: |
          touch .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> env.txt
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> env.txt
          echo "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}" >> env.txt
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> env.txt
          echo "DB_AUTH_TOKEN=${{ secrets.DB_AUTH_TOKEN }}" >> env.txt
          echo "JWT_PASSWORD=${{ secrets.JWT_PASSWORD }}" >> env.txt
          echo "URL_DATABASE=${{ secrets.URL_DATABASE }}" >> env.txt

      - name: List files
        run: ls -a

      - name: Show content
        run: sudo cat env.txt

      - name: Create remote directory
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" "mkdir -p /home/ec2-user/drive-backend/"

      - name: Copy all files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* "${EC2_USER}@${EC2_IP}:/home/ec2-user/drive-backend/"

      - name: Rename env.txt to .env on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" "mv /home/ec2-user/drive-backend/env.txt /home/ec2-user/drive-backend/.env"

      - name: SSH into EC2 and Install Node.js
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" << 'EOF'
            curl -sL https://rpm.nodesource.com/setup_22.x | sudo -E bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2
            exit
          EOF

      - name: SSH into EC2 and Start Node.js Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" << 'EOF'
            cd /home/ec2-user/drive-backend/
            npm install
            npm run build
            sudo pm2 stop "drive-backend" || true
            sudo pm2 start dist/index.js --name "drive-backend"
            pm2 save
            exit
          EOF
