name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2
    env:
      EC2_IP: ${{ secrets.EC2_IP }}
      EC2_USER: ${{ secrets.EC2_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa 
      - name: Ensure write permissions
        run: |
          chmod 777 .
      - name: Create remote directory
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" "mkdir -p /home/ec2-user/drive-backend/"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* "${EC2_USER}@${EC2_IP}:/home/ec2-user/drive-backend/"

      - name: SSH into EC2 and Install Node.js
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" << 'EOF'
            curl -sL https://rpm.nodesource.com/setup_22.x | sudo -E bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2
            exit
          EOF

      - name: SSH into EC2 and Start Node.js Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${EC2_USER}@${EC2_IP}" << 'EOF'
            cd /home/ec2-user/drive-backend/
            npm install
            npm run build
            sudo pm2 start dist/index.js --name "drive-backend"
            pm2 save
            exit
          EOF
